openapi: 3.0.0
info:
  title: Admin Helper
  version: '0.2'
servers:
  - url: 'https://admin-helper-backend.herokuapp.com/api/v1'
  - url: 'http://localhost:3000/api/v1/'
tags:
  - name: Login
  - name: Forget Password
  - name: Employee
  - name: Day Off Category
  - name: Day Off Info
  - name: Day Off Request
paths:
  '/day-off-categories':
    get:
      tags:
        - Day Off Category
      summary: Get List DayOffCategories
      description: Returns List DayOffCategories
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties: 
                  employee:
                    $ref: '#/components/schemas/DayOffCategory'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Permission'
  '/employees/{id}':
    get:
      tags:
        - Employees
      summary: Find employee by id
      description: Returns an employee
      operationId: getEmployeeById
      parameters:
        - name: id
          in: path
          description: ID of employee to return
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties: 
                  employee:
                    $ref: '#/components/schemas/Employee'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Permission'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      tags:
        - Employees
      summary: Update employee by id
      description: Returns an employee
      parameters:
        - name: id
          in: path
          description: ID of employee to return
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                encrypted_password:
                  type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties: 
                  employee:
                    $ref: '#/components/schemas/Employee'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Permission'
        '404':
          $ref: '#/components/responses/NotFound'
  /login:
    post:
      tags:
        - Login
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
            example: 'admin@gmail.com'
        - name: password
          in: query
          required: true
          schema:
            type: string
            example: '123456'
      responses:
        '200':
          description: Will send `Authenticated`
          content:
            appclication/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    $ref: '#/components/schemas/Employee'
        '400':
          $ref: '#/components/responses/BadRequest'
  /password:
    post:
      tags:
        - Forget Password
      summary: Step 1 Send Mail
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/RequestSuccess'
        '404':
          $ref: '#/components/responses/NotFound'
  /password/validate_token:
    post:
      tags:
        - Forget Password
      summary: Step 2 Verify Token
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
        - name: token
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/RequestSuccess'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
  '/password/{id}':
    patch:
      tags:
        - Forget Password
      summary: 'Step 3 Verify Token, Reset Password'
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
        - name: token
          in: query
          required: true
          schema:
            type: string
        - name: new_password
          in: query
          required: true
          schema:
            type: string
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          $ref: '#/components/responses/RequestSuccess'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
  /employees/{id}/day-off-requests/:
    post:
      tags:
      - Day Off Request
      parameters:
        - name: id
          in: path
          description: Employee ID
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      summary: Create new DayOffRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DayOffRequest'
      responses:
        '201':
          description: created day-off-request
          content:
            application/json:
              schema:
                type: object
                properties: 
                  employee:
                    $ref: '#/components/schemas/DayOffRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Permission'
        '404':
          $ref: '#/components/responses/NotFound'
  '/day-off-infos/{id}':
    patch:
      tags:
      - Day Off Info
      parameters:
        - name: id
          in: path
          description: DayOffInfo ID
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      summary: Update DayOffInfo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DayOffInfo'
      responses:
        '200':
          $ref: '#/components/responses/RequestSuccess'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Permission'
        '404':
          $ref: '#/components/responses/NotFound'
  /employees:
    get:
        tags:
          - Employees
        summary: Get list employee
        description: Returns list employee
        parameters:
          - name: search
            in: query
            description: Search with first name or last name
            required: false
            schema:
              type: string
          - name: status
            in: query
            description: Search with status
            required: false
            schema:
              type: string
          - name: birthday_from
            in: query
            description: Search with birthday from
            required: false
            schema:
              type: string
              format: date
              example: '2015-11-23'
          - name: birthday_to
            in: query
            description: Search with birthday to
            required: false
            schema:
              type: string
              format: date
              example: '2015-11-23'
          - name: joined_company_date_from
            in: query
            description: Search with joined company date from
            required: false
            schema:
              type: string
              format: date
              example: '2015-11-23'
          - name: joined_company_date_to
            in: query
            description: Search with joined company date to
            required: false
            schema:
              type: string
              format: date
              example: '2015-11-23'
            
          - name: day_off_from_date
            in: query
            description: Search with joined company date to
            required: false
            schema:
              type: string
              format: date
              example: '2015-11-23'
          - name: day_off_to_date
            in: query
            description: Search with joined company date to
            required: false
            schema:
              type: string
              format: date
              example: '2015-11-23'
          - name: page
            in: query
            description: pagination with the current page
            required: false
            schema:
              type: integer
              example: 1
          - name: per_page
            in: query
            description: pagination with the number of elements per page
            required: false
            schema:
              type: integer
              example: 20
          - name: sort
            in: query
            description: Sort with properties
            required: false
            schema:
              type: string
              example: 'first_name:DESC, last_name:ASC'
        responses:
          '200':
            description: successful
            content:
              application/json:
                schema:
                  type: object
                  properties: 
                    data:
                      type: array
                      items:
                        type: object
                        $ref: '#/components/schemas/Employee'
                    pagination:
                      $ref: '#/components/schemas/Pagination'
          '401':
            $ref: '#/components/responses/Unauthorized'
          '403':
            $ref: '#/components/responses/Permission'
    post: 
      tags:
        - Employees
      summary: Create employee
      description: Returns list employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestParamCreateEmployee'
      responses:
          '200':
            description: successful
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Employee'
          '401':
            $ref: '#/components/responses/Unauthorized'
          '403':
            $ref: '#/components/responses/Permission'
          '422':
            $ref: '#/components/responses/InvalidParams'
  '/employees/{id}/status':
    patch:
      tags:
        - Employees
      summary: Update employee by ID
      description: Returns a single pet
      parameters:
        - name: id
          in: path
          description: ID of user to return
          required: true
          schema:
            type: integer
        - name: status
          in: query
          description: Status of employee
          required: true
          schema:
            type: string
            enum: [ACTIVE, FORMER]
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties: 
                  employee:
                    $ref: '#/components/schemas/Employee'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Permission'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/InvalidParams'
components:
  responses:
    RequestSuccess:
      description: Request Success
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 422
              message:
                type: string
                example: "Request Success"
            required:
              - code
              - message
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 404
              message:
                type: string
                example: "Couldn't find User"
            required:
              - code
              - message
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              message:
                type: string
                example: "User authentication failed"
            required:
              - code
              - message
    Permission:
      description: You do not have permission
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 403
              message:
                type: string
                example: "You do not have permission"
            required:
              - code
              - message
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              message:
                type: string
                example: "Bad Request"
            required:
              - code
              - message
    InvalidParams:
      description: Invalid Params
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 422
              message:
                type: string
                example: "Invalid Params"
            required:
              - code
              - message
  schemas:
    RequestParamCreateEmployee:
      type: object
      properties:
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        birthdate:
          type: string
          format: date
        join_date:
          type: string
          format: date
        status:
          type: string
          enum: [ACTIVE, FORMER]
        phone_number:
          type: string
        roles:
          type: array
          items:
            type: string
            example: EMPLOYEE
        day_off_infos:
          type: array
          items:
            type: object
            properties:
              day_off_category_id: 
                type: integer
                example: 1
              hours: 
                type: integer
                example: 160
    Pagination:
      type: object
      properties:
        current_page:
          type: integer
          example: 1
        page_size:
          type: integer
          example: 1
        total_pages:
          type: integer
          example: 1
        total_count:
          type: integer
          example: 1
    DayOffCategory:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
    DayOffInfo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        hours:
          type: integer
          format: int64
        day_off_category_id:
          type: integer
          format: int64
    Employee:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        birthdate:
          type: string
          format: date
        join_date:
          type: string
          format: date
        status:
          type: string
          enum: [ACTIVE, FORMER]
        phone_number:
          type: string
        roles:
          type: array
          items:
            type: string
        hours:
          type: array
          items:
            type: object
    DayOffRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64
        from_date:
          type: string
          format: date
          example: '2020-02-02'
        to_date:
          type: string
          format: date
          example: '2020-02-10'
        hours_per_day:
          type: string
          format: int64
          example: 4
        notes:
          type: string
          example: "here is notes"
        day_off_info_id:
          type: string
          format: int64
          example: 1
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
