openapi: 3.0.0
info:
  title: Admin Helper
  version: "0.2"
servers:
- url: https://admin-helper-backend.herokuapp.com/api/v1
- url: http://localhost:3000/api/v1/
security:
- Bearer: []
tags:
- name: Login
- name: Employees
paths:
  /employees/{id}:
    get:
      tags:
      - Employees
      summary: Find user by ID
      description: Returns a single pet
      operationId: getUserById
      parameters:
      - name: id
        in: path
        description: ID of user to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content: {}
        403:
          description: You do not have permission
          content: {}
        404:
          description: User not found
          content: {}
  /login:
    post:
      tags:
      - Login
      parameters:
      - name: email
        in: query
        required: true
        schema:
          type: string
      - name: password
        in: query
        required: true
        schema:
          type: string
      responses:
        200:
          description: Will send `Authenticated`
          content: {}
        400:
          description: Invalid username/password supplied    
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        encrypted_password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        birthdate:
          type: string
          format: date
        join_date:
          type: string
          format: date
        status:
          type: string
        phone_number:
          type: string
        roles:
          type: string
        reset_password_token:
          type: string
        reset_password_sent_at:
          type: string
          format: datetime
      xml:
        name: User
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header