employee:
admin:
  employees:
    - index
    - show
    - create
    - update
    - update_status
  sessions:
    - create
  day_off_request:
    - create
    - index
  day_off_info:
    - update
  day_off_categories:
    - index
  device_categories:
    - index
    - show
    - create
    - destroy
    - update
  device_histories:
    - index
    - show
  devices:
    - create
    - show
    - index
    - destroy
    - update
    - discard
    - move_to_inventory
super_admin: