employee:
admin:
  employees:
    - index
    - show
    - create
    - update
    - update_status
  sessions:
    - create
  day_off_request:
    - create
    - index
  day_off_info:
    - update
  day_off_categories:
    - index
  device_categories:
    - index
    - show
    - create
    - destroy
  device_histories:
    - index
    - show
  devices:
    - create
    - show
    - index
    - update
super_admin: