employee:
  sessions:
    - create
  day_off_request:
    - create
    - cancel
admin:
  employees:
    - index
    - show
    - create
    - update
    - update_status
    - update_password
  sessions:
    - create
    - google_login
  day_off_request:
    - create
    - index
    - update
    - destroy
    - approve
    - deny
  day_off_info:
    - create
    - update
    - index
    - deactivate
  day_off_categories:
    - index
    - update
    - deactivate
    - activate
    - create
  device_categories:
    - index
    - show
    - create
    - update
  device_histories:
    - index
    - show
  devices:
    - create
    - show
    - index
    - destroy
    - update
    - assign
    - discard
    - move_to_inventory
super_admin: