employee:
admin:
  employees:
    - index
    - show
    - create
    - update
    - update_status
  sessions:
    - create
  day_off_request:
    - create
    - index
  day_off_info:
    - update
  day_off_categories:
    - index
  device_histories:
    - index
  devices:
    - create
    - index
super_admin: